# Generated by Django 4.2.4 on 2023-09-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('demand', models.IntegerField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pHub.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('available_capacity', models.IntegerField()),
                ('total_distance', models.FloatField()),
                ('assigned_clients', models.ManyToManyField(to='pHub.node')),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pHub.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('servers', models.ManyToManyField(to='pHub.server')),
            ],
        ),
    ]
