# Generated by Django 4.2.4 on 2023-09-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinate',
            new_name='CoordinateI',
        ),
        migrations.RenameModel(
            old_name='Node',
            new_name='NodeI',
        ),
        migrations.RenameModel(
            old_name='Server',
            new_name='ServerI',
        ),
        migrations.RenameModel(
            old_name='Solution',
            new_name='SolutionI',
        ),
    ]
