# Generated by Django 4.2.4 on 2023-09-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pHub', '0002_rename_coordinate_coordinatei_rename_node_nodei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalNodes', models.PositiveIntegerField()),
                ('totalServers', models.PositiveIntegerField()),
                ('maxCapacityServer', models.PositiveIntegerField()),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pHub.nodei')),
            ],
        ),
    ]
