# Generated by Django 4.2.4 on 2023-09-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pHub', '0004_alter_problemi_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemi',
            name='nodes',
        ),
        migrations.AddField(
            model_name='problemi',
            name='nodes',
            field=models.ManyToManyField(to='pHub.nodei'),
        ),
    ]
