# Generated by Django 4.2.4 on 2023-09-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pHub', '0005_remove_problemi_nodes_problemi_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodei',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='problemi',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='serveri',
            name='assigned_clients',
        ),
        migrations.RemoveField(
            model_name='serveri',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='solutioni',
            name='servers',
        ),
        migrations.DeleteModel(
            name='CoordinateI',
        ),
        migrations.DeleteModel(
            name='NodeI',
        ),
        migrations.DeleteModel(
            name='ProblemI',
        ),
        migrations.DeleteModel(
            name='ServerI',
        ),
        migrations.DeleteModel(
            name='SolutionI',
        ),
    ]
